name: Continuous Deployment

on:
  pull_request:
    branches: [ "dev" ]
    types: [closed]

permissions: write-all

jobs:
  
  QA-JOB:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    environment: QA
    
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2

      - name: Run Sample Script
        run: | 
          echo "QA job running"

  PROD-JOB:

    if: github.event.pull_request.merged == true
    
    runs-on: ubuntu-latest
    environment: PROD
    needs: QA-JOB
    
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
      
      - name: Run Sample Script
        run: | 
          echo "PROD job running"


