name: Continuous Deployment

on:
  pull_request:
    branches: [ "dev" ]
    types: [closed]

permissions: write-all

jobs:
  
  QA-JOB:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    environment: QA
    
    steps:
      - name: Checkout code from dev
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Install Packages
        run: make install

      - name: Train
        run: make train

      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval

      - name: Run Tests
        run: make unit_test

  PROD-JOB:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    environment: PROD
    needs: QA-JOB
    
    steps:
      - name: Checkout code from dev
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup CML
        uses: iterative/setup-cml@v2
      
      - name: Run Sample Script
        run: | 
          echo "PROD job running"
