

name: Continuous Deployment

on:
  pull_request:
    branches: [ "dev" ]
    types: [closed]

permissions: write-all

jobs:
  
  QA-JOB:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    environment: QA
    
    steps:
      - name: Checkout code from DEV
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Run Tests
        run: make unit_test

  PROD-JOB:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    environment: PROD
    needs: QA-JOB
    
    steps:
      - name: Checkout code from DEV
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup CML
        uses: iterative/setup-cml@v2
      
      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: make deploy HF_TOKEN=$HF_TOKEN
