name: Continuous Integration

on:
  pull_request:
    branches: [ "dev" ]

permissions: write-all

jobs:
  DEV-JOB:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Install Packages
        run: make install
      - name: Format Code
        run: make format
      - name: Transform Data
        run: make transform_data
      - name: Train
        run: make train
      - name: Test
        run: make test
      - name: Visualize
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make visualize